databases:
  - name: Carrentals
    databaseName: carrentals
    user: carrentals_user

services:
  - type: web
    name: CarRental
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Carrentals
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false